# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 21:19
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
