# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170421_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
